'on': push
name: "\U0001F680 Deploy website on push"
jobs:
  web-deploy:
    name: "\U0001F389 Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: "\U0001F69A Get latest code"
        uses: actions/checkout@v3
      - name: "\U0001F4C2 Sync files"
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: '${{ secrets.server_host }}'
          username: '${{ secrets.ftp_username }}'
          password: '${{ secrets.ftp_password }}'
          server-dir: /site/wwwroot/
          log-level: verbose
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.vscode/**