name: Prettier Check

on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  prettier-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Prettier Check
        uses: docker://node:latest
        with:
          args: bash -c "yarn global add prettier && prettier --check ."
